batch_size: 4096
checkpoint_dir: /home/andrei/Documents/visualSCode/aml-andrei/results/Small_HI_20250427_173704/checkpoints
data: Small_HI
data_path: /home/andrei/Documents/visualSCode/aml-andrei/data
device: !!python/object/apply:torch.device
- cuda
- 0
dropout: 0.08340440094051481
emlps: false
epochs: 100
final_dropout: 0.28812979737686323
log_dir: /home/andrei/Documents/visualSCode/aml-andrei/results/Small_HI_20250427_173704/logs
loss: ce
lr: 0.0006116418195373612
model: pna
n_epochs: 100
n_gnn_layers: 2
n_hidden: 20
num_neighs:
- 100
- 100
output_dir: /home/andrei/Documents/visualSCode/aml-andrei/results
run_dir: /home/andrei/Documents/visualSCode/aml-andrei/results/Small_HI_20250427_173704
save_model: false
seed: 1
testing: false
w_ce1: 1.0003967674742307
w_ce2: 7.077633468006714
